use buffa_codegen::idents::{escape_mod_ident, make_field_ident};
use connectrpc_codegen::plugin::CodeGeneratorResponseFile;
use heck::ToSnakeCase;
use proc_macro2::TokenStream;
use quote::quote;
use syn::{Ident, Path, Type};
use uni_error::UniError;

use crate::error::{CodegenErrKind, CodegenResult};
use crate::ir::{CommentSet, DescriptorIr, HttpVerb, Method, ProtoFile, Service};
use crate::options::CodegenOptions;
use crate::resolver::TypeResolver;
use crate::shape::{
    FileShapes, GeneratedDto, RequestPartShape, RequestShape, ShapeField, plan_file_shapes,
};

const REST_MODULE_SUFFIX: &str = "_rest";
const ROUTER_FUNCTION_NAME: &str = "make_router";

pub(crate) fn generate_file(
    ir: &DescriptorIr,
    file_name: &str,
    options: &CodegenOptions,
) -> CodegenResult<Option<CodeGeneratorResponseFile>> {
    let proto_file = ir.file(file_name).ok_or_else(|| {
        UniError::from_kind_context(
            CodegenErrKind::FileToGenerateNotFound,
            format!("file_to_generate {file_name:?} was not present in proto_file"),
        )
    })?;

    if !proto_file.has_http_bindings() {
        return Ok(None);
    }

    let output_name = output_file_name(proto_file.name.as_ref());
    let content = RustGenerator::new(ir, proto_file, options)?.generate()?;

    Ok(Some(CodeGeneratorResponseFile {
        name: Some(output_name),
        content: Some(content),
        ..Default::default()
    }))
}

fn output_file_name(proto_file_name: &str) -> String {
    let stem = proto_file_name
        .strip_suffix(".proto")
        .unwrap_or(proto_file_name);
    format!("{stem}.connect2axum.rs")
}

struct RustGenerator<'a> {
    proto_file: &'a ProtoFile,
    options: &'a CodegenOptions,
    resolver: TypeResolver<'a>,
    shapes: FileShapes,
}

impl<'a> RustGenerator<'a> {
    fn new(
        ir: &'a DescriptorIr,
        proto_file: &'a ProtoFile,
        options: &'a CodegenOptions,
    ) -> CodegenResult<Self> {
        Ok(Self {
            proto_file,
            options,
            resolver: TypeResolver::new(ir, options),
            shapes: plan_file_shapes(ir, proto_file, options)?,
        })
    }

    fn generate(&self) -> CodegenResult<String> {
        let modules = self
            .proto_file
            .services
            .iter()
            .filter(|service| service.has_http_bindings())
            .map(|service| self.service_module(service))
            .collect::<CodegenResult<Vec<_>>>()?;
        let source = format_tokens(quote! {
            #(#modules)*
        })?;

        Ok(format!(
            "// @generated by connect2axum.\n\
             // This file is generated from {}. Do not edit by hand.\n\n\
             {source}",
            self.proto_file.name.as_ref()
        ))
    }

    fn service_module(&self, service: &Service) -> CodegenResult<TokenStream> {
        let module_ident = parse_ident(
            &service_module_name(service.name.as_ref()),
            "generated REST module",
        )?;
        let dto_items = self
            .shapes
            .generated_dtos
            .iter()
            .map(dto_tokens)
            .collect::<CodegenResult<Vec<_>>>()?;
        let handler_items = service
            .methods
            .iter()
            .filter(|method| method.http.is_some())
            .map(|method| self.handler_tokens(service, method))
            .collect::<CodegenResult<Vec<_>>>()?;
        let router_item = self.router_tokens(service)?;
        let not_implemented = not_implemented_response_tokens();

        Ok(quote! {
            /// Generated axum handlers and router.
            pub mod #module_ident {
                #![allow(unused_imports)]

                use std::sync::Arc;

                use axum::extract::{Path, Query, State};
                use axum::Json;
                use http::{Extensions, HeaderMap};

                #(#dto_items)*

                #(#handler_items)*

                #router_item

                #not_implemented
            }
        })
    }

    fn handler_tokens(&self, service: &Service, method: &Method) -> CodegenResult<TokenStream> {
        let shape = self.shape_for(method)?;
        let service_trait = parse_path(
            self.resolver
                .connect_service_trait(service.full_name.as_ref())
                .as_str(),
            "Connect service trait",
        )?;
        let method_ident = parse_ident(
            self.resolver.method_fn_name(method.name.as_ref()).as_ref(),
            "handler function",
        )?;
        let service_value = parse_ident(
            self.resolver.value_ident("service", self.options).as_ref(),
            "service binding",
        )?;
        let path_value = parse_ident(
            self.resolver.value_ident("path", self.options).as_ref(),
            "path binding",
        )?;
        let query_value = parse_ident(
            self.resolver.value_ident("query", self.options).as_ref(),
            "query binding",
        )?;
        let headers_value = parse_ident(
            self.resolver.value_ident("headers", self.options).as_ref(),
            "headers binding",
        )?;
        let extensions_value = parse_ident(
            self.resolver
                .value_ident("extensions", self.options)
                .as_ref(),
            "extensions binding",
        )?;
        let body_value = parse_ident(
            self.resolver.value_ident("body", self.options).as_ref(),
            "body binding",
        )?;

        let mut params = vec![quote! {
            State(#service_value): State<Arc<S>>
        }];
        let mut unused_bindings = vec![quote! {
            let _ = #service_value;
        }];

        if let Some(path_type) = path_extractor_type(&shape.path_fields)? {
            params.push(quote! {
                Path(#path_value): Path<#path_type>
            });
            unused_bindings.push(quote! {
                let _ = #path_value;
            });
        }

        if let Some(query_type) = shape.query_shape.as_ref().map(part_type).transpose()? {
            params.push(quote! {
                Query(#query_value): Query<#query_type>
            });
            unused_bindings.push(quote! {
                let _ = #query_value;
            });
        }

        params.push(quote! {
            #headers_value: HeaderMap
        });
        params.push(quote! {
            #extensions_value: Extensions
        });
        unused_bindings.push(quote! {
            let _ = #headers_value;
        });
        unused_bindings.push(quote! {
            let _ = #extensions_value;
        });

        if let Some(body_type) = shape.body_shape.as_ref().map(part_type).transpose()? {
            params.push(quote! {
                Json(#body_value): Json<#body_type>
            });
            unused_bindings.push(quote! {
                let _ = #body_value;
            });
        }

        Ok(quote! {
            async fn #method_ident<S>(
                #(#params),*
            ) -> http::Response<axum::body::Body>
            where
                S: #service_trait + Send + Sync + 'static,
            {
                #(#unused_bindings)*
                not_implemented_response()
            }
        })
    }

    fn router_tokens(&self, service: &Service) -> CodegenResult<TokenStream> {
        let service_trait = parse_path(
            self.resolver
                .connect_service_trait(service.full_name.as_ref())
                .as_str(),
            "Connect service trait",
        )?;
        let router_ident = parse_ident(ROUTER_FUNCTION_NAME, "router function")?;
        let route_calls = service
            .methods
            .iter()
            .filter(|method| method.http.is_some())
            .map(|method| self.route_tokens(method))
            .collect::<CodegenResult<Vec<_>>>()?;

        Ok(quote! {
            pub fn #router_ident<S>(service: Arc<S>) -> axum::Router
            where
                S: #service_trait + Send + Sync + 'static,
            {
                axum::Router::new()
                    #(#route_calls)*
                    .with_state(service)
            }
        })
    }

    fn route_tokens(&self, method: &Method) -> CodegenResult<TokenStream> {
        let binding = method.http.as_ref().ok_or_else(|| {
            UniError::from_kind_context(
                CodegenErrKind::InvalidDescriptor,
                format!("method {} has no HTTP binding", method.full_name.as_ref()),
            )
        })?;
        let path = binding.path.as_ref();
        let method_ident = parse_ident(
            self.resolver.method_fn_name(method.name.as_ref()).as_ref(),
            "route handler",
        )?;

        let route = match binding.verb {
            HttpVerb::Get => quote! {
                .route(#path, axum::routing::get(#method_ident::<S>))
            },
            HttpVerb::Post => quote! {
                .route(#path, axum::routing::post(#method_ident::<S>))
            },
            HttpVerb::Put => quote! {
                .route(#path, axum::routing::put(#method_ident::<S>))
            },
            HttpVerb::Delete => quote! {
                .route(#path, axum::routing::delete(#method_ident::<S>))
            },
            HttpVerb::Patch => quote! {
                .route(#path, axum::routing::patch(#method_ident::<S>))
            },
        };

        Ok(route)
    }

    fn shape_for(&self, method: &Method) -> CodegenResult<&RequestShape> {
        self.shapes
            .request_shapes
            .iter()
            .find(|shape| shape.method == method.full_name)
            .ok_or_else(|| {
                UniError::from_kind_context(
                    CodegenErrKind::InvalidDescriptor,
                    format!(
                        "request shape for {} was not planned",
                        method.full_name.as_ref()
                    ),
                )
            })
    }
}

fn dto_tokens(dto: &GeneratedDto) -> CodegenResult<TokenStream> {
    let comments = comment_attrs(&dto.comments);
    let dto_ident = parse_ident(dto.name.as_ref(), "generated DTO")?;
    let fields = dto
        .fields
        .iter()
        .map(dto_field_tokens)
        .collect::<CodegenResult<Vec<_>>>()?;

    Ok(quote! {
        #(#comments)*
        #[derive(Clone, Debug, serde::Deserialize)]
        pub struct #dto_ident {
            #(#fields),*
        }
    })
}

fn dto_field_tokens(field: &ShapeField) -> CodegenResult<TokenStream> {
    let comments = comment_attrs(&field.field.comments);
    let field_ident = parse_ident(
        &make_field_ident(field.field.name.as_ref()).to_string(),
        "DTO field",
    )?;
    let field_type = parse_type(field.rust_type.as_str(), "DTO field type")?;

    Ok(quote! {
        #(#comments)*
        pub #field_ident: #field_type
    })
}

fn not_implemented_response_tokens() -> TokenStream {
    quote! {
        fn not_implemented_response() -> http::Response<axum::body::Body> {
            http::Response::builder()
                .status(http::StatusCode::NOT_IMPLEMENTED)
                .body(axum::body::Body::from("not implemented"))
                .expect("static not implemented response should build")
        }
    }
}

fn comment_attrs(comments: &CommentSet) -> Vec<TokenStream> {
    comments
        .leading_detached
        .iter()
        .chain(comments.leading.iter())
        .flat_map(|comment| comment.lines())
        .map(str::trim_end)
        .filter(|line| !line.is_empty())
        .map(|line| {
            quote! {
                #[doc = #line]
            }
        })
        .collect()
}

fn service_module_name(service_name: &str) -> String {
    format!(
        "{}{REST_MODULE_SUFFIX}",
        escape_mod_ident(&service_name.to_snake_case())
    )
}

fn path_extractor_type(path_fields: &[ShapeField]) -> CodegenResult<Option<Type>> {
    match path_fields {
        [] => Ok(None),
        [field] => parse_type(field.rust_type.as_str(), "path extractor type").map(Some),
        fields => {
            let field_types = fields
                .iter()
                .map(|field| parse_type(field.rust_type.as_str(), "path extractor type"))
                .collect::<CodegenResult<Vec<_>>>()?;
            parse_quoted_type(quote! {
                (#(#field_types),*)
            })
            .map(Some)
        }
    }
}

fn part_type(part: &RequestPartShape) -> CodegenResult<Type> {
    let rust_type = match part {
        RequestPartShape::VerbatimRequest { rust_type }
        | RequestPartShape::ExistingMessage { rust_type, .. }
        | RequestPartShape::GeneratedDto { rust_type, .. } => rust_type,
    };
    parse_type(rust_type.as_str(), "request part type")
}

fn parse_ident(value: &str, context: &'static str) -> CodegenResult<Ident> {
    syn::parse_str(value).map_err(|err| {
        UniError::from_kind_context(
            CodegenErrKind::InvalidDescriptor,
            format!("{context} identifier {value:?} did not parse: {err}"),
        )
    })
}

fn parse_path(value: &str, context: &'static str) -> CodegenResult<Path> {
    syn::parse_str(value).map_err(|err| {
        UniError::from_kind_context(
            CodegenErrKind::InvalidDescriptor,
            format!("{context} path {value:?} did not parse: {err}"),
        )
    })
}

fn parse_type(value: &str, context: &'static str) -> CodegenResult<Type> {
    syn::parse_str(value).map_err(|err| {
        UniError::from_kind_context(
            CodegenErrKind::InvalidDescriptor,
            format!("{context} {value:?} did not parse: {err}"),
        )
    })
}

fn parse_quoted_type(tokens: TokenStream) -> CodegenResult<Type> {
    syn::parse2(tokens.clone()).map_err(|err| {
        UniError::from_kind_context(
            CodegenErrKind::InvalidDescriptor,
            format!("generated Rust type {tokens} did not parse: {err}"),
        )
    })
}

fn format_tokens(tokens: TokenStream) -> CodegenResult<String> {
    let file = syn::parse2(tokens.clone()).map_err(|err| {
        UniError::from_kind_context(
            CodegenErrKind::InvalidDescriptor,
            format!("generated Rust file did not parse: {err}\n{tokens}"),
        )
    })?;
    Ok(prettyplease::unparse(&file))
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::process::Command;
    use std::time::{SystemTime, UNIX_EPOCH};

    use buffa::encoding::{Tag, WireType};
    use buffa::{MessageField, UnknownField, UnknownFieldData};
    use connectrpc_codegen::codegen::descriptor::{
        DescriptorProto, EnumDescriptorProto, FieldDescriptorProto, FileDescriptorProto,
        MethodDescriptorProto, MethodOptions, ServiceDescriptorProto,
        field_descriptor_proto::{Label, Type},
    };

    use crate::{CodeGeneratorRequest, try_generate};

    #[test]
    fn generates_expected_rust_skeleton() {
        let content = generated_content();

        assert_eq!(
            content,
            r#"// @generated by connect2axum.
// This file is generated from test/v1/test.proto. Do not edit by hand.

/// Generated axum handlers and router.
pub mod test_service_rest {
    #![allow(unused_imports)]
    use std::sync::Arc;
    use axum::extract::{Path, Query, State};
    use axum::Json;
    use http::{Extensions, HeaderMap};
    #[derive(Clone, Debug, serde::Deserialize)]
    pub struct TestRequestQuery__ {
        pub test_type: crate::proto::test::v1::Tester,
        pub tester: crate::proto::test::v1::Nested,
    }
    async fn get_one<S>(
        State(service__): State<Arc<S>>,
        Path(path__): Path<::std::string::String>,
        Query(query__): Query<TestRequestQuery__>,
        headers__: HeaderMap,
        extensions__: Extensions,
    ) -> http::Response<axum::body::Body>
    where
        S: crate::connect::test::v1::TestService + Send + Sync + 'static,
    {
        let _ = service__;
        let _ = path__;
        let _ = query__;
        let _ = headers__;
        let _ = extensions__;
        not_implemented_response()
    }
    async fn do_test<S>(
        State(service__): State<Arc<S>>,
        Path(path__): Path<(::std::string::String, crate::proto::test::v1::Tester)>,
        headers__: HeaderMap,
        extensions__: Extensions,
        Json(body__): Json<crate::proto::test::v1::Nested>,
    ) -> http::Response<axum::body::Body>
    where
        S: crate::connect::test::v1::TestService + Send + Sync + 'static,
    {
        let _ = service__;
        let _ = path__;
        let _ = headers__;
        let _ = extensions__;
        let _ = body__;
        not_implemented_response()
    }
    pub fn make_router<S>(service: Arc<S>) -> axum::Router
    where
        S: crate::connect::test::v1::TestService + Send + Sync + 'static,
    {
        axum::Router::new()
            .route("/test/{data}", axum::routing::get(get_one::<S>))
            .route("/test/{data}/testing/{test_type}", axum::routing::post(do_test::<S>))
            .with_state(service)
    }
    fn not_implemented_response() -> http::Response<axum::body::Body> {
        http::Response::builder()
            .status(http::StatusCode::NOT_IMPLEMENTED)
            .body(axum::body::Body::from("not implemented"))
            .expect("static not implemented response should build")
    }
}
"#
        );
    }

    #[test]
    fn generated_skeleton_compiles_in_temp_crate() {
        let content = generated_content();
        let temp_dir = temp_crate_dir();
        fs::create_dir_all(temp_dir.join("src")).expect("temp src dir");
        fs::write(temp_dir.join("Cargo.toml"), temp_cargo_toml()).expect("temp Cargo.toml");
        fs::write(temp_dir.join("src/lib.rs"), temp_lib_rs(&content)).expect("temp lib.rs");

        let output = Command::new("cargo")
            .args(["check", "--quiet"])
            .current_dir(&temp_dir)
            .output()
            .expect("cargo check runs");

        if !output.status.success() {
            panic!(
                "generated crate did not compile\nstdout:\n{}\nstderr:\n{}\nsource:\n{}",
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr),
                content
            );
        }

        fs::remove_dir_all(temp_dir).expect("remove temp crate");
    }

    fn generated_content() -> String {
        let request = request();
        let response = try_generate(&request).unwrap();
        assert_eq!(response.file.len(), 1);
        response.file[0]
            .content
            .as_ref()
            .expect("generated file has content")
            .clone()
    }

    fn request() -> CodeGeneratorRequest {
        CodeGeneratorRequest {
            file_to_generate: vec!["test/v1/test.proto".into()],
            proto_file: vec![test_file()],
            ..Default::default()
        }
    }

    fn test_file() -> FileDescriptorProto {
        FileDescriptorProto {
            name: Some("test/v1/test.proto".into()),
            package: Some("test.v1".into()),
            message_type: vec![
                DescriptorProto {
                    name: Some("TestRequest".into()),
                    field: vec![
                        field("data", 1, Type::TYPE_STRING, None),
                        field("test_type", 2, Type::TYPE_ENUM, Some(".test.v1.Tester")),
                        field("tester", 8, Type::TYPE_MESSAGE, Some(".test.v1.Nested")),
                    ],
                    ..Default::default()
                },
                DescriptorProto {
                    name: Some("Nested".into()),
                    ..Default::default()
                },
            ],
            enum_type: vec![EnumDescriptorProto {
                name: Some("Tester".into()),
                ..Default::default()
            }],
            service: vec![ServiceDescriptorProto {
                name: Some("TestService".into()),
                method: vec![
                    method("GetOne", http_rule(2, "/test/{data}", None)),
                    method(
                        "DoTest",
                        http_rule(4, "/test/{data}/testing/{test_type}", Some("tester")),
                    ),
                ],
                ..Default::default()
            }],
            ..Default::default()
        }
    }

    fn method(name: &str, options: MessageField<MethodOptions>) -> MethodDescriptorProto {
        MethodDescriptorProto {
            name: Some(name.into()),
            input_type: Some(".test.v1.TestRequest".into()),
            output_type: Some(".test.v1.TestResponse".into()),
            options,
            ..Default::default()
        }
    }

    fn field(name: &str, number: i32, kind: Type, type_name: Option<&str>) -> FieldDescriptorProto {
        FieldDescriptorProto {
            name: Some(name.into()),
            number: Some(number),
            label: Some(Label::LABEL_OPTIONAL),
            r#type: Some(kind),
            type_name: type_name.map(str::to_owned),
            json_name: Some(name.into()),
            ..Default::default()
        }
    }

    fn http_rule(verb_field: u32, path: &str, body: Option<&str>) -> MessageField<MethodOptions> {
        let mut rule = Vec::new();
        Tag::new(verb_field, WireType::LengthDelimited).encode(&mut rule);
        buffa::types::encode_string(path, &mut rule);

        if let Some(body) = body {
            Tag::new(7, WireType::LengthDelimited).encode(&mut rule);
            buffa::types::encode_string(body, &mut rule);
        }

        let mut options = MethodOptions::default();
        options.__buffa_unknown_fields.push(UnknownField {
            number: 72_295_728,
            data: UnknownFieldData::LengthDelimited(rule),
        });
        MessageField::some(options)
    }

    fn temp_crate_dir() -> std::path::PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time")
            .as_nanos();
        std::env::temp_dir().join(format!(
            "connect2axum-codegen-{}-{nanos}",
            std::process::id()
        ))
    }

    fn temp_cargo_toml() -> &'static str {
        r#"[package]
name = "connect2axum-generated-check"
version = "0.0.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
"#
    }

    fn temp_lib_rs(generated: &str) -> String {
        format!(
            r#"extern crate self as axum;
extern crate self as http;

pub struct Json<T>(pub T);

pub mod body {{
    #[derive(Clone, Debug)]
    pub struct Body;

    impl Body {{
        pub fn from<T>(_value: T) -> Self {{
            Self
        }}
    }}
}}

pub mod extract {{
    pub struct Path<T>(pub T);
    pub struct Query<T>(pub T);
    pub struct State<T>(pub T);
}}

pub mod routing {{
    pub struct MethodRouter;

    pub fn delete<H>(_handler: H) -> MethodRouter {{
        MethodRouter
    }}

    pub fn get<H>(_handler: H) -> MethodRouter {{
        MethodRouter
    }}

    pub fn patch<H>(_handler: H) -> MethodRouter {{
        MethodRouter
    }}

    pub fn post<H>(_handler: H) -> MethodRouter {{
        MethodRouter
    }}

    pub fn put<H>(_handler: H) -> MethodRouter {{
        MethodRouter
    }}
}}

pub struct Router;

impl Router {{
    pub fn new() -> Self {{
        Self
    }}

    pub fn route(self, _path: &str, _method: routing::MethodRouter) -> Self {{
        self
    }}

    pub fn with_state<S>(self, _state: S) -> Self {{
        self
    }}
}}

pub struct HeaderMap;
pub struct Extensions;

pub struct StatusCode;

impl StatusCode {{
    pub const NOT_IMPLEMENTED: Self = Self;
}}

pub struct Response<T>(pub T);
pub struct Builder;

impl Response<body::Body> {{
    pub fn builder() -> Builder {{
        Builder
    }}
}}

impl Builder {{
    pub fn status(self, _status: StatusCode) -> Self {{
        self
    }}

    pub fn body(self, body: body::Body) -> Result<Response<body::Body>, ()> {{
        Ok(Response(body))
    }}
}}

pub mod connect {{
    pub mod test {{
        pub mod v1 {{
            pub trait TestService: Send + Sync + 'static {{}}
        }}
    }}
}}

pub mod proto {{
    pub mod test {{
        pub mod v1 {{
            #[derive(Clone, Debug, serde::Deserialize)]
            pub struct TestRequest;

            #[derive(Clone, Debug, serde::Deserialize)]
            pub struct Nested;

            #[derive(Clone, Debug, serde::Deserialize)]
            pub enum Tester {{}}
        }}
    }}
}}

{generated}
"#
        )
    }
}
