use buffa_codegen::idents::{escape_mod_ident, make_field_ident};
use connectrpc_codegen::plugin::CodeGeneratorResponseFile;
use heck::ToSnakeCase;
use proc_macro2::TokenStream;
use quote::quote;
use syn::{Ident, Path, Type};
use uni_error::UniError;

use crate::error::{CodegenErrKind, CodegenResult};
use crate::ir::{
    CommentSet, DescriptorIr, Field, FieldKind, FieldLabel, HttpBody, HttpVerb, Method, ProtoFile,
    Service,
};
use crate::options::CodegenOptions;
use crate::resolver::TypeResolver;
use crate::shape::{
    FieldSource, FileShapes, GeneratedDto, RequestPartShape, RequestReconstruction, RequestShape,
    ShapeField, plan_file_shapes,
};

const REST_MODULE_SUFFIX: &str = "_rest";
const ROUTER_FUNCTION_NAME: &str = "make_router";

pub(crate) fn generate_file(
    ir: &DescriptorIr,
    file_name: &str,
    options: &CodegenOptions,
) -> CodegenResult<Option<CodeGeneratorResponseFile>> {
    let proto_file = ir.file(file_name).ok_or_else(|| {
        UniError::from_kind_context(
            CodegenErrKind::FileToGenerateNotFound,
            format!("file_to_generate {file_name:?} was not present in proto_file"),
        )
    })?;

    if !proto_file.has_http_bindings() {
        return Ok(None);
    }

    let output_name = output_file_name(proto_file.name.as_ref());
    let content = RustGenerator::new(ir, proto_file, options)?.generate()?;

    Ok(Some(CodeGeneratorResponseFile {
        name: Some(output_name),
        content: Some(content),
        ..Default::default()
    }))
}

fn output_file_name(proto_file_name: &str) -> String {
    let stem = proto_file_name
        .strip_suffix(".proto")
        .unwrap_or(proto_file_name);
    format!("{stem}.connect2axum.rs")
}

struct RustGenerator<'a> {
    proto_file: &'a ProtoFile,
    options: &'a CodegenOptions,
    resolver: TypeResolver<'a>,
    shapes: FileShapes,
}

impl<'a> RustGenerator<'a> {
    fn new(
        ir: &'a DescriptorIr,
        proto_file: &'a ProtoFile,
        options: &'a CodegenOptions,
    ) -> CodegenResult<Self> {
        Ok(Self {
            proto_file,
            options,
            resolver: TypeResolver::new(ir, options),
            shapes: plan_file_shapes(ir, proto_file, options)?,
        })
    }

    fn generate(&self) -> CodegenResult<String> {
        let compatible_body_items = self.compatible_body_items()?;
        let modules = self
            .proto_file
            .services
            .iter()
            .filter(|service| service.has_http_bindings())
            .map(|service| self.service_module(service))
            .collect::<CodegenResult<Vec<_>>>()?;
        let source = format_tokens(quote! {
            #(#compatible_body_items)*
            #(#modules)*
        })?;

        Ok(format!(
            "// @generated by connect2axum.\n\
             // This file is generated from {}. Do not edit by hand.\n\n\
             {source}",
            self.proto_file.name.as_ref()
        ))
    }

    fn service_module(&self, service: &Service) -> CodegenResult<TokenStream> {
        let module_ident = parse_ident(
            &service_module_name(service.name.as_ref()),
            "generated REST module",
        )?;
        let dto_items = self
            .shapes
            .generated_dtos
            .iter()
            .map(dto_tokens)
            .collect::<CodegenResult<Vec<_>>>()?;
        let handler_items = service
            .methods
            .iter()
            .filter(|method| method.http.is_some())
            .map(|method| self.handler_tokens(service, method))
            .collect::<CodegenResult<Vec<_>>>()?;
        let router_item = self.router_tokens(service)?;

        Ok(quote! {
            /// Generated axum handlers and router.
            pub mod #module_ident {
                #![allow(unused_imports)]

                use std::sync::Arc;

                use axum::extract::{FromRequestParts, Path, Query, State};

                #(#dto_items)*

                #(#handler_items)*

                #router_item
            }
        })
    }

    fn compatible_body_items(&self) -> CodegenResult<Vec<TokenStream>> {
        let mut output_types = Vec::new();

        for service in &self.proto_file.services {
            for method in &service.methods {
                if method.http.is_some()
                    && !output_types
                        .iter()
                        .any(|output_type: &String| output_type == method.output_type.as_ref())
                {
                    output_types.push(method.output_type.as_ref().to_owned());
                }
            }
        }

        output_types
            .iter()
            .map(|output_type| self.compatible_body_item(output_type))
            .collect()
    }

    fn compatible_body_item(&self, output_type_name: &str) -> CodegenResult<TokenStream> {
        let output_type = parse_type(
            self.resolver.owned_message_type(output_type_name)?.as_str(),
            "method output type",
        )?;
        let output_view_type = parse_type(
            &format!(
                "{}<'_>",
                self.resolver.view_message_type(output_type_name)?.as_str()
            ),
            "method output view type",
        )?;
        let output_owned_view_type = parse_type(
            &format!(
                "::buffa::view::OwnedView<{}<'static>>",
                self.resolver.view_message_type(output_type_name)?.as_str()
            ),
            "method output owned view type",
        )?;

        Ok(quote! {
            impl ::connect2axum::JsonCompatibleBody<#output_type> for #output_view_type {
                fn encode_proto(&self) -> ::buffa::bytes::Bytes {
                    ::buffa::ViewEncode::encode_to_bytes(self)
                }
            }

            impl ::connect2axum::JsonCompatibleBody<#output_type> for #output_owned_view_type {
                fn encode_proto(&self) -> ::buffa::bytes::Bytes {
                    ::buffa::ViewEncode::encode_to_bytes(&**self)
                }
            }
        })
    }

    fn handler_tokens(&self, service: &Service, method: &Method) -> CodegenResult<TokenStream> {
        let shape = self.shape_for(method)?;
        let service_trait = parse_path(
            self.resolver
                .connect_service_trait(service.full_name.as_ref())
                .as_str(),
            "Connect service trait",
        )?;
        let method_ident = parse_ident(
            self.resolver.method_fn_name(method.name.as_ref()).as_ref(),
            "handler function",
        )?;
        let service_value = parse_ident(
            self.resolver.value_ident("service", self.options).as_ref(),
            "service binding",
        )?;
        let request_value = parse_ident(
            self.resolver.value_ident("request", self.options).as_ref(),
            "request binding",
        )?;
        let ctx_value = parse_ident(
            self.resolver.value_ident("ctx", self.options).as_ref(),
            "context binding",
        )?;
        let query_value = parse_ident(
            self.resolver.value_ident("query", self.options).as_ref(),
            "query binding",
        )?;
        let body_value = parse_ident(
            self.resolver.value_ident("body", self.options).as_ref(),
            "body binding",
        )?;
        let http_request_value = parse_ident(
            self.resolver
                .value_ident("http_request", self.options)
                .as_ref(),
            "HTTP request binding",
        )?;
        let parts_value = parse_ident(
            self.resolver.value_ident("parts", self.options).as_ref(),
            "HTTP request parts binding",
        )?;
        let body_stream_value = parse_ident(
            self.resolver
                .value_ident("body_stream", self.options)
                .as_ref(),
            "HTTP request body binding",
        )?;
        let body_bytes_value = parse_ident(
            self.resolver
                .value_ident("body_bytes", self.options)
                .as_ref(),
            "HTTP request body bytes binding",
        )?;
        let runtime = parse_path(self.options.runtime_module.as_ref(), "runtime module")?;
        let output_type = parse_type(
            self.resolver
                .owned_message_type(method.output_type.as_ref())?
                .as_str(),
            "method output type",
        )?;
        let request_view_type = parse_type(
            &format!("{}<'static>", shape.request_view_type.as_str()),
            "method request view type",
        )?;
        let bindings = RequestSetupBindings {
            request: &request_value,
            query: &query_value,
            body: &body_value,
            body_bytes: &body_bytes_value,
            parts: &parts_value,
            body_stream: &body_stream_value,
        };
        let direct_request = direct_request_tokens(
            method,
            shape,
            &bindings,
            &self.resolver,
            self.options,
            &runtime,
            &request_view_type,
        )?;
        let uses_direct_request = direct_request.is_some();

        let request_setup = if let Some(direct_request) = direct_request {
            direct_request
        } else {
            fallback_request_setup_tokens(
                shape,
                &bindings,
                &self.resolver,
                self.options,
                &runtime,
                &request_view_type,
            )?
        };
        let needs_mut_parts = !uses_direct_request && !shape.path_fields.is_empty();
        let parts_binding = if needs_mut_parts {
            quote! { mut #parts_value }
        } else {
            quote! { #parts_value }
        };
        let body_binding = if shape.body_shape.is_some() {
            quote! { #body_stream_value }
        } else {
            quote! { _body_stream__ }
        };

        Ok(quote! {
            pub async fn #method_ident<S>(
                State(#service_value): State<Arc<S>>,
                #http_request_value: http::Request<axum::body::Body>,
            ) -> http::Response<axum::body::Body>
            where
                S: #service_trait + Send + Sync + 'static,
            {
                let (#parts_binding, #body_binding) = #http_request_value.into_parts();
                #request_setup
                let #ctx_value = #runtime::request_context(
                    #parts_value.headers,
                    #parts_value.extensions,
                );

                #runtime::compatible_service_response::<#output_type, _>(
                    #service_value.#method_ident(#ctx_value, #request_value).await
                )
            }
        })
    }

    fn router_tokens(&self, service: &Service) -> CodegenResult<TokenStream> {
        let service_trait = parse_path(
            self.resolver
                .connect_service_trait(service.full_name.as_ref())
                .as_str(),
            "Connect service trait",
        )?;
        let router_ident = parse_ident(ROUTER_FUNCTION_NAME, "router function")?;
        let route_calls = service
            .methods
            .iter()
            .filter(|method| method.http.is_some())
            .map(|method| self.route_tokens(method))
            .collect::<CodegenResult<Vec<_>>>()?;

        Ok(quote! {
            pub fn #router_ident<S>(service: Arc<S>) -> axum::Router
            where
                S: #service_trait + Send + Sync + 'static,
            {
                axum::Router::new()
                    #(#route_calls)*
                    .with_state(service)
            }
        })
    }

    fn route_tokens(&self, method: &Method) -> CodegenResult<TokenStream> {
        let binding = method.http.as_ref().ok_or_else(|| {
            UniError::from_kind_context(
                CodegenErrKind::InvalidDescriptor,
                format!("method {} has no HTTP binding", method.full_name.as_ref()),
            )
        })?;
        let path = binding.path.as_ref();
        let method_ident = parse_ident(
            self.resolver.method_fn_name(method.name.as_ref()).as_ref(),
            "route handler",
        )?;

        let route = match binding.verb {
            HttpVerb::Get => quote! {
                .route(#path, axum::routing::get(#method_ident::<S>))
            },
            HttpVerb::Post => quote! {
                .route(#path, axum::routing::post(#method_ident::<S>))
            },
            HttpVerb::Put => quote! {
                .route(#path, axum::routing::put(#method_ident::<S>))
            },
            HttpVerb::Delete => quote! {
                .route(#path, axum::routing::delete(#method_ident::<S>))
            },
            HttpVerb::Patch => quote! {
                .route(#path, axum::routing::patch(#method_ident::<S>))
            },
        };

        Ok(route)
    }

    fn shape_for(&self, method: &Method) -> CodegenResult<&RequestShape> {
        self.shapes
            .request_shapes
            .iter()
            .find(|shape| shape.method == method.full_name)
            .ok_or_else(|| {
                UniError::from_kind_context(
                    CodegenErrKind::InvalidDescriptor,
                    format!(
                        "request shape for {} was not planned",
                        method.full_name.as_ref()
                    ),
                )
            })
    }
}

fn dto_tokens(dto: &GeneratedDto) -> CodegenResult<TokenStream> {
    let comments = comment_attrs(&dto.comments);
    let dto_ident = parse_ident(dto.name.as_ref(), "generated DTO")?;
    let fields = dto
        .fields
        .iter()
        .map(dto_field_tokens)
        .collect::<CodegenResult<Vec<_>>>()?;

    Ok(quote! {
        #(#comments)*
        #[derive(Clone, Debug, serde::Deserialize)]
        pub struct #dto_ident {
            #(#fields),*
        }
    })
}

fn dto_field_tokens(field: &ShapeField) -> CodegenResult<TokenStream> {
    let comments = comment_attrs(&field.field.comments);
    let field_ident = parse_ident(
        &make_field_ident(field.field.name.as_ref()).to_string(),
        "DTO field",
    )?;
    let field_type = parse_type(field.rust_type.as_str(), "DTO field type")?;

    Ok(quote! {
        #(#comments)*
        pub #field_ident: #field_type
    })
}

fn comment_attrs(comments: &CommentSet) -> Vec<TokenStream> {
    comments
        .leading_detached
        .iter()
        .chain(comments.leading.iter())
        .flat_map(|comment| comment.lines())
        .map(str::trim_end)
        .filter(|line| !line.is_empty())
        .map(|line| {
            quote! {
                #[doc = #line]
            }
        })
        .collect()
}

fn service_module_name(service_name: &str) -> String {
    format!(
        "{}{REST_MODULE_SUFFIX}",
        escape_mod_ident(&service_name.to_snake_case())
    )
}

struct RequestSetupBindings<'a> {
    request: &'a Ident,
    query: &'a Ident,
    body: &'a Ident,
    body_bytes: &'a Ident,
    parts: &'a Ident,
    body_stream: &'a Ident,
}

fn fallback_request_setup_tokens(
    shape: &RequestShape,
    bindings: &RequestSetupBindings<'_>,
    resolver: &TypeResolver<'_>,
    options: &CodegenOptions,
    runtime: &Path,
    request_view_type: &Type,
) -> CodegenResult<TokenStream> {
    let request_value = bindings.request;
    let query_value = bindings.query;
    let body_value = bindings.body;
    let body_bytes_value = bindings.body_bytes;
    let parts_value = bindings.parts;
    let body_stream_value = bindings.body_stream;
    let mut setup = Vec::new();

    if let Some(path_statement) =
        path_extractor_statement(shape, resolver, options, parts_value, runtime)?
    {
        setup.push(path_statement);
    }

    if let Some(query_statement) =
        query_extractor_statement(shape, query_value, parts_value, runtime)?
    {
        setup.push(query_statement);
    }

    if let Some(body_statement) = body_extractor_statement(
        shape,
        body_value,
        body_bytes_value,
        body_stream_value,
        runtime,
    )? {
        setup.push(body_statement);
    }

    let request_reconstruction = request_reconstruction_tokens(
        shape,
        request_value,
        query_value,
        body_value,
        resolver,
        options,
    )?;

    Ok(quote! {
        #(#setup)*
        #request_reconstruction
        let #request_value = match #runtime::owned_view::<#request_view_type>(&#request_value) {
            Ok(#request_value) => #request_value,
            Err(err) => return #runtime::error_response(err),
        };
    })
}

fn path_extractor_statement(
    shape: &RequestShape,
    resolver: &TypeResolver<'_>,
    options: &CodegenOptions,
    parts_value: &Ident,
    runtime: &Path,
) -> CodegenResult<Option<TokenStream>> {
    match shape.path_fields.as_slice() {
        [] => Ok(None),
        [field] => {
            let binding = path_field_binding(field, resolver, options)?;
            let field_type = parse_type(field.rust_type.as_str(), "path extractor type")?;
            Ok(Some(quote! {
                let #binding = match <Path<#field_type> as FromRequestParts<()>>::from_request_parts(
                    &mut #parts_value,
                    &(),
                ).await {
                    Ok(Path(#binding)) => #binding,
                    Err(err) => {
                        return #runtime::error_response(::connectrpc::ConnectError::invalid_argument(
                            format!("failed to decode REST path parameters: {err}"),
                        ));
                    }
                };
            }))
        }
        fields => {
            let bindings = fields
                .iter()
                .map(|field| path_field_binding(field, resolver, options))
                .collect::<CodegenResult<Vec<_>>>()?;
            let field_types = fields
                .iter()
                .map(|field| parse_type(field.rust_type.as_str(), "path extractor type"))
                .collect::<CodegenResult<Vec<_>>>()?;
            let tuple_type = parse_quoted_type(quote! {
                (#(#field_types),*)
            })?;
            Ok(Some(quote! {
                let (#(#bindings),*) = match <Path<#tuple_type> as FromRequestParts<()>>::from_request_parts(
                    &mut #parts_value,
                    &(),
                ).await {
                    Ok(Path((#(#bindings),*))) => (#(#bindings),*),
                    Err(err) => {
                        return #runtime::error_response(::connectrpc::ConnectError::invalid_argument(
                            format!("failed to decode REST path parameters: {err}"),
                        ));
                    }
                };
            }))
        }
    }
}

fn query_extractor_statement(
    shape: &RequestShape,
    query_value: &Ident,
    parts_value: &Ident,
    runtime: &Path,
) -> CodegenResult<Option<TokenStream>> {
    let Some(query_type) = shape.query_shape.as_ref().map(part_type).transpose()? else {
        return Ok(None);
    };

    Ok(Some(quote! {
        let #query_value = match Query::<#query_type>::try_from_uri(&#parts_value.uri) {
            Ok(Query(#query_value)) => #query_value,
            Err(err) => {
                return #runtime::error_response(::connectrpc::ConnectError::invalid_argument(
                    format!("failed to decode REST query parameters: {err}"),
                ));
            }
        };
    }))
}

fn body_extractor_statement(
    shape: &RequestShape,
    body_value: &Ident,
    body_bytes_value: &Ident,
    body_stream_value: &Ident,
    runtime: &Path,
) -> CodegenResult<Option<TokenStream>> {
    let Some(body_type) = shape.body_shape.as_ref().map(part_type).transpose()? else {
        return Ok(None);
    };

    Ok(Some(quote! {
        let #body_bytes_value = match #runtime::body_bytes(#body_stream_value).await {
            Ok(#body_bytes_value) => #body_bytes_value,
            Err(err) => return #runtime::error_response(err),
        };
        let #body_value = match #runtime::json_body::<#body_type>(&#body_bytes_value) {
            Ok(#body_value) => #body_value,
            Err(err) => return #runtime::error_response(err),
        };
    }))
}

fn request_reconstruction_tokens(
    shape: &RequestShape,
    request_value: &Ident,
    query_value: &Ident,
    body_value: &Ident,
    resolver: &TypeResolver<'_>,
    options: &CodegenOptions,
) -> CodegenResult<TokenStream> {
    let request_type = parse_type(shape.request_type.as_str(), "method request type")?;

    match &shape.reconstruction {
        RequestReconstruction::Empty => Ok(quote! {
            let #request_value = #request_type::default();
        }),
        RequestReconstruction::VerbatimBody => Ok(quote! {
            let #request_value = #body_value;
        }),
        RequestReconstruction::VerbatimQuery => Ok(quote! {
            let #request_value = #query_value;
        }),
        RequestReconstruction::FromParts { fields } => {
            let assignments = fields
                .iter()
                .map(|assignment| {
                    let field_ident = parse_ident(
                        &make_field_ident(assignment.field.as_ref()).to_string(),
                        "request field",
                    )?;
                    let value = field_source_expr(
                        assignment.field.as_ref(),
                        assignment.source,
                        shape,
                        query_value,
                        body_value,
                        resolver,
                        options,
                    )?;
                    Ok(quote! {
                        #field_ident: #value
                    })
                })
                .collect::<CodegenResult<Vec<_>>>()?;

            Ok(quote! {
                let #request_value = #request_type {
                    #(#assignments,)*
                    ..::core::default::Default::default()
                };
            })
        }
    }
}

fn direct_request_tokens(
    method: &Method,
    shape: &RequestShape,
    bindings: &RequestSetupBindings<'_>,
    resolver: &TypeResolver<'_>,
    options: &CodegenOptions,
    runtime: &Path,
    request_view_type: &Type,
) -> CodegenResult<Option<TokenStream>> {
    let request_value = bindings.request;
    let parts_value = bindings.parts;
    let body_stream_value = bindings.body_stream;
    let body_bytes_value = bindings.body_bytes;

    match &shape.reconstruction {
        RequestReconstruction::Empty => Ok(Some(quote! {
            let #request_value = match #runtime::owned_view_from_bytes::<#request_view_type>(
                ::buffa::bytes::Bytes::new(),
            ) {
                Ok(#request_value) => #request_value,
                Err(err) => return #runtime::error_response(err),
            };
        })),
        RequestReconstruction::FromParts { fields } => {
            let binding = method.http.as_ref().ok_or_else(|| {
                UniError::from_kind_context(
                    CodegenErrKind::InvalidDescriptor,
                    format!("method {} has no HTTP binding", method.full_name.as_ref()),
                )
            })?;
            if !fields.iter().all(|field| {
                direct_field(shape, field.field.as_ref())
                    .is_some_and(|field| is_direct_string_field(&field.field))
            }) {
                return Ok(None);
            }
            if !fields.iter().all(|field| {
                field.source != FieldSource::Body
                    || matches!(&binding.body, HttpBody::Field(body_field)
                        if body_field.as_ref() == field.field.as_ref())
            }) {
                return Ok(None);
            }

            let mut writes = Vec::new();
            if !shape.path_fields.is_empty() {
                let path_decoder_value = parse_ident(
                    resolver.value_ident("path", options).as_ref(),
                    "path decoder binding",
                )?;
                let path_captures = path_capture_bounds(binding.path.as_ref(), &shape.path_fields)?;
                let mut path_writes = Vec::new();
                for (field, capture) in shape.path_fields.iter().zip(path_captures) {
                    if !fields
                        .iter()
                        .any(|assignment| assignment.field.as_ref() == field.field.name.as_ref())
                    {
                        continue;
                    }
                    let field_number = field_number(&field.field)?;
                    let field_binding = path_field_binding(field, resolver, options)?;
                    let prefix = capture.prefix;
                    let suffix = capture.suffix;
                    path_writes.push(quote! {
                        let #field_binding = match #path_decoder_value.capture(#prefix, #suffix) {
                            Ok(#field_binding) => #field_binding,
                            Err(err) => return #runtime::error_response(err),
                        };
                        if let Err(err) = #request_value.push_path_string(
                            #field_number,
                            #field_binding,
                        ) {
                            return #runtime::error_response(err);
                        }
                    });
                }
                writes.push(quote! {
                    let mut #path_decoder_value = #runtime::PathDecoder::new(#parts_value.uri.path());
                    #(#path_writes)*
                });
            }

            for assignment in fields {
                let field = direct_field(shape, assignment.field.as_ref()).ok_or_else(|| {
                    UniError::from_kind_context(
                        CodegenErrKind::InvalidDescriptor,
                        format!(
                            "request field {} was not found in planned direct request parts",
                            assignment.field.as_ref()
                        ),
                    )
                })?;
                let field_number = field_number(&field.field)?;
                match assignment.source {
                    FieldSource::Path => {}
                    FieldSource::Query => {
                        let json_name = field.field.json_name.as_ref();
                        let proto_name = field.field.name.as_ref();
                        writes.push(quote! {
                            #request_value.push_query_string(
                                #parts_value.uri.query(),
                                #json_name,
                                #proto_name,
                                #field_number,
                            );
                        });
                    }
                    FieldSource::Body => {
                        writes.push(quote! {
                            let #body_bytes_value = match #runtime::body_bytes(#body_stream_value).await {
                                Ok(#body_bytes_value) => #body_bytes_value,
                                Err(err) => return #runtime::error_response(err),
                            };
                            if let Err(err) = #request_value.push_json_body_string(
                                &#body_bytes_value,
                                #field_number,
                            ) {
                                return #runtime::error_response(err);
                            }
                        });
                    }
                }
            }

            Ok(Some(quote! {
                let mut #request_value = #runtime::WireRequest::new();
                #(#writes)*
                let #request_value = match #runtime::owned_view_from_wire::<#request_view_type>(
                    #request_value,
                ) {
                    Ok(#request_value) => #request_value,
                    Err(err) => return #runtime::error_response(err),
                };
            }))
        }
        RequestReconstruction::VerbatimBody | RequestReconstruction::VerbatimQuery => Ok(None),
    }
}

fn direct_field(shape: &RequestShape, field_name: &str) -> Option<ShapeField> {
    shape
        .path_fields
        .iter()
        .chain(part_fields(shape.query_shape.as_ref()))
        .chain(part_fields(shape.body_shape.as_ref()))
        .find(|field| field.field.name.as_ref() == field_name)
        .cloned()
}

fn part_fields(part: Option<&RequestPartShape>) -> &[ShapeField] {
    match part {
        Some(RequestPartShape::GeneratedDto { fields, .. }) => fields,
        Some(RequestPartShape::ExistingMessage { field, .. }) => std::slice::from_ref(field),
        Some(RequestPartShape::VerbatimRequest { .. }) | None => &[],
    }
}

fn is_direct_string_field(field: &Field) -> bool {
    field.kind == FieldKind::String && field.label != Some(FieldLabel::Repeated)
}

fn field_number(field: &Field) -> CodegenResult<u32> {
    field
        .number
        .and_then(|number| number.try_into().ok())
        .ok_or_else(|| {
            UniError::from_kind_context(
                CodegenErrKind::InvalidDescriptor,
                format!(
                    "field {} does not have a valid field number",
                    field.name.as_ref()
                ),
            )
        })
}

struct PathCaptureBounds {
    prefix: String,
    suffix: String,
}

fn path_capture_bounds(
    path_template: &str,
    fields: &[ShapeField],
) -> CodegenResult<Vec<PathCaptureBounds>> {
    let mut cursor = 0;
    let mut captures = Vec::with_capacity(fields.len());

    for field in fields {
        let marker = format!("{{{}}}", field.field.name.as_ref());
        let marker_start = path_template[cursor..]
            .find(&marker)
            .map(|offset| cursor + offset)
            .ok_or_else(|| {
                UniError::from_kind_context(
                    CodegenErrKind::InvalidDescriptor,
                    format!(
                        "path template {path_template:?} did not contain field marker {marker:?}"
                    ),
                )
            })?;
        let marker_end = marker_start + marker.len();
        let prefix = path_template[cursor..marker_start].to_owned();
        let suffix_end = path_template[marker_end..]
            .find('{')
            .map(|offset| marker_end + offset)
            .unwrap_or(path_template.len());
        let suffix = path_template[marker_end..suffix_end].to_owned();

        captures.push(PathCaptureBounds { prefix, suffix });
        cursor = suffix_end;
    }

    Ok(captures)
}

fn field_source_expr(
    field_name: &str,
    source: FieldSource,
    shape: &RequestShape,
    query_value: &Ident,
    body_value: &Ident,
    resolver: &TypeResolver<'_>,
    options: &CodegenOptions,
) -> CodegenResult<TokenStream> {
    match source {
        FieldSource::Path => {
            let binding = parse_ident(
                resolver.value_ident(field_name, options).as_ref(),
                "path field binding",
            )?;
            Ok(quote! { #binding })
        }
        FieldSource::Body => part_field_expr(field_name, shape.body_shape.as_ref(), body_value),
        FieldSource::Query => part_field_expr(field_name, shape.query_shape.as_ref(), query_value),
    }
}

fn part_field_expr(
    field_name: &str,
    part: Option<&RequestPartShape>,
    binding: &Ident,
) -> CodegenResult<TokenStream> {
    match part {
        Some(RequestPartShape::GeneratedDto { .. }) => {
            let field_ident = parse_ident(
                &make_field_ident(field_name).to_string(),
                "generated DTO field",
            )?;
            Ok(quote! { #binding.#field_ident })
        }
        Some(RequestPartShape::ExistingMessage { field, .. })
            if field.field.name.as_ref() == field_name =>
        {
            Ok(quote! { #binding })
        }
        Some(RequestPartShape::VerbatimRequest { .. }) => {
            let field_ident = parse_ident(
                &make_field_ident(field_name).to_string(),
                "request part field",
            )?;
            Ok(quote! { #binding.#field_ident })
        }
        _ => Err(UniError::from_kind_context(
            CodegenErrKind::InvalidDescriptor,
            format!("request field {field_name} was not found in planned request part"),
        )),
    }
}

fn path_field_binding(
    field: &ShapeField,
    resolver: &TypeResolver<'_>,
    options: &CodegenOptions,
) -> CodegenResult<Ident> {
    parse_ident(
        resolver
            .value_ident(field.field.name.as_ref(), options)
            .as_ref(),
        "path field binding",
    )
}

fn part_type(part: &RequestPartShape) -> CodegenResult<Type> {
    let rust_type = match part {
        RequestPartShape::VerbatimRequest { rust_type }
        | RequestPartShape::ExistingMessage { rust_type, .. }
        | RequestPartShape::GeneratedDto { rust_type, .. } => rust_type,
    };
    parse_type(rust_type.as_str(), "request part type")
}

fn parse_ident(value: &str, context: &'static str) -> CodegenResult<Ident> {
    syn::parse_str(value).map_err(|err| {
        UniError::from_kind_context(
            CodegenErrKind::InvalidDescriptor,
            format!("{context} identifier {value:?} did not parse: {err}"),
        )
    })
}

fn parse_path(value: &str, context: &'static str) -> CodegenResult<Path> {
    syn::parse_str(value).map_err(|err| {
        UniError::from_kind_context(
            CodegenErrKind::InvalidDescriptor,
            format!("{context} path {value:?} did not parse: {err}"),
        )
    })
}

fn parse_type(value: &str, context: &'static str) -> CodegenResult<Type> {
    syn::parse_str(value).map_err(|err| {
        UniError::from_kind_context(
            CodegenErrKind::InvalidDescriptor,
            format!("{context} {value:?} did not parse: {err}"),
        )
    })
}

fn parse_quoted_type(tokens: TokenStream) -> CodegenResult<Type> {
    syn::parse2(tokens.clone()).map_err(|err| {
        UniError::from_kind_context(
            CodegenErrKind::InvalidDescriptor,
            format!("generated Rust type {tokens} did not parse: {err}"),
        )
    })
}

fn format_tokens(tokens: TokenStream) -> CodegenResult<String> {
    let file = syn::parse2(tokens.clone()).map_err(|err| {
        UniError::from_kind_context(
            CodegenErrKind::InvalidDescriptor,
            format!("generated Rust file did not parse: {err}\n{tokens}"),
        )
    })?;
    Ok(prettyplease::unparse(&file))
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::process::Command;
    use std::time::{SystemTime, UNIX_EPOCH};

    use buffa::encoding::{Tag, WireType};
    use buffa::{MessageField, UnknownField, UnknownFieldData};
    use connectrpc_codegen::codegen::descriptor::{
        DescriptorProto, EnumDescriptorProto, FieldDescriptorProto, FileDescriptorProto,
        MethodDescriptorProto, MethodOptions, ServiceDescriptorProto,
        field_descriptor_proto::{Label, Type},
    };

    use crate::{CodeGeneratorRequest, try_generate};

    #[test]
    #[ignore = "kept as a historical snapshot; phase 8 assertions cover the active shape"]
    fn generates_expected_rust_skeleton() {
        let content = generated_content();

        assert_eq!(
            content,
            r#"// @generated by connect2axum.
// This file is generated from test/v1/test.proto. Do not edit by hand.

/// Generated axum handlers and router.
pub mod test_service_rest {
    #![allow(unused_imports)]
    use std::sync::Arc;
    use axum::extract::{Path, Query, State};
    use axum::Json;
    use http::{Extensions, HeaderMap};
    #[derive(Clone, Debug, serde::Deserialize)]
    pub struct TestRequestQuery__ {
        pub test_type: crate::proto::test::v1::Tester,
        pub tester: crate::proto::test::v1::Nested,
    }
    pub async fn get_one<S>(
        State(service__): State<Arc<S>>,
        Path(data__): Path<::std::string::String>,
        Query(query__): Query<TestRequestQuery__>,
        headers__: HeaderMap,
        extensions__: Extensions,
    ) -> http::Response<axum::body::Body>
    where
        S: crate::connect::test::v1::TestService + Send + Sync + 'static,
    {
        let ctx__ = ::connect2axum::request_context(headers__, extensions__);
        let request__ = crate::proto::test::v1::TestRequest {
            data: data__,
            test_type: query__.test_type,
            tester: query__.tester,
            ..::core::default::Default::default()
        };
        let request__ = match ::connect2axum::owned_view::<
            crate::proto::test::v1::__buffa::view::TestRequestView<'static>,
        >(&request__) {
            Ok(request__) => request__,
            Err(err) => return ::connect2axum::error_response(err),
        };
        ::connect2axum::service_response::<
            crate::proto::test::v1::TestResponse,
            _,
        >(service__.get_one(ctx__, request__).await)
    }
    pub async fn do_test<S>(
        State(service__): State<Arc<S>>,
        Path(
            (data__, test_type__),
        ): Path<(::std::string::String, crate::proto::test::v1::Tester)>,
        headers__: HeaderMap,
        extensions__: Extensions,
        Json(body__): Json<crate::proto::test::v1::Nested>,
    ) -> http::Response<axum::body::Body>
    where
        S: crate::connect::test::v1::TestService + Send + Sync + 'static,
    {
        let ctx__ = ::connect2axum::request_context(headers__, extensions__);
        let request__ = crate::proto::test::v1::TestRequest {
            data: data__,
            test_type: test_type__,
            tester: body__,
            ..::core::default::Default::default()
        };
        let request__ = match ::connect2axum::owned_view::<
            crate::proto::test::v1::__buffa::view::TestRequestView<'static>,
        >(&request__) {
            Ok(request__) => request__,
            Err(err) => return ::connect2axum::error_response(err),
        };
        ::connect2axum::service_response::<
            crate::proto::test::v1::TestResponse,
            _,
        >(service__.do_test(ctx__, request__).await)
    }
    pub async fn patch_all<S>(
        State(service__): State<Arc<S>>,
        headers__: HeaderMap,
        extensions__: Extensions,
        Json(body__): Json<crate::proto::test::v1::TestRequest>,
    ) -> http::Response<axum::body::Body>
    where
        S: crate::connect::test::v1::TestService + Send + Sync + 'static,
    {
        let ctx__ = ::connect2axum::request_context(headers__, extensions__);
        let request__ = body__;
        let request__ = match ::connect2axum::owned_view::<
            crate::proto::test::v1::__buffa::view::TestRequestView<'static>,
        >(&request__) {
            Ok(request__) => request__,
            Err(err) => return ::connect2axum::error_response(err),
        };
        ::connect2axum::service_response::<
            crate::proto::test::v1::TestResponse,
            _,
        >(service__.patch_all(ctx__, request__).await)
    }
    pub async fn ping<S>(
        State(service__): State<Arc<S>>,
        headers__: HeaderMap,
        extensions__: Extensions,
    ) -> http::Response<axum::body::Body>
    where
        S: crate::connect::test::v1::TestService + Send + Sync + 'static,
    {
        let ctx__ = ::connect2axum::request_context(headers__, extensions__);
        let request__ = crate::proto::test::v1::EmptyRequest::default();
        let request__ = match ::connect2axum::owned_view::<
            crate::proto::test::v1::__buffa::view::EmptyRequestView<'static>,
        >(&request__) {
            Ok(request__) => request__,
            Err(err) => return ::connect2axum::error_response(err),
        };
        ::connect2axum::service_response::<
            crate::proto::test::v1::TestResponse,
            _,
        >(service__.ping(ctx__, request__).await)
    }
    pub fn make_router<S>(service: Arc<S>) -> axum::Router
    where
        S: crate::connect::test::v1::TestService + Send + Sync + 'static,
    {
        axum::Router::new()
            .route("/test/{data}", axum::routing::get(get_one::<S>))
            .route("/test/{data}/testing/{test_type}", axum::routing::post(do_test::<S>))
            .route("/test", axum::routing::patch(patch_all::<S>))
            .route("/ping", axum::routing::get(ping::<S>))
            .with_state(service)
    }
}
"#
        );
    }

    #[test]
    fn generates_phase_8_rust_skeleton() {
        let content = generated_content();

        assert!(content.contains("impl ::connect2axum::JsonCompatibleBody"));
        assert!(content.contains("::connect2axum::compatible_service_response::<"));
        assert!(content.contains("::connect2axum::owned_view_from_bytes::<"));
        assert!(content.contains("use axum::extract::{FromRequestParts, Path, Query, State};"));
        assert!(content.contains("http_request__: http::Request<axum::body::Body>"));
    }

    #[test]
    fn generates_direct_string_request_transcoder() {
        let mut file = test_file();
        file.message_type[0].field = vec![
            field("data", 1, Type::TYPE_STRING, None),
            field("test_type", 2, Type::TYPE_STRING, None),
            field("tester", 8, Type::TYPE_STRING, None),
        ];
        file.enum_type.clear();
        let response = try_generate(&CodeGeneratorRequest {
            file_to_generate: vec!["test/v1/test.proto".into()],
            proto_file: vec![file],
            ..Default::default()
        })
        .unwrap();
        let content = response.file[0].content.as_ref().unwrap();

        assert!(content.contains("http_request__: http::Request<axum::body::Body>"));
        assert!(content.contains("::connect2axum::PathDecoder::new(parts__.uri.path())"));
        assert!(content.contains(".push_path_string("));
        assert!(content.contains(".push_query_string("));
        assert!(content.contains(".push_json_body_string("));
        assert!(content.contains("::connect2axum::owned_view_from_wire::<"));
    }

    #[test]
    fn generated_handlers_compile_and_call_service() {
        let content = generated_content();
        let temp_dir = temp_crate_dir();
        fs::create_dir_all(temp_dir.join("src")).expect("temp src dir");
        fs::write(temp_dir.join("Cargo.toml"), temp_cargo_toml()).expect("temp Cargo.toml");
        fs::write(temp_dir.join("src/lib.rs"), temp_lib_rs(&content)).expect("temp lib.rs");

        let output = Command::new("cargo")
            .args(["test", "--quiet"])
            .current_dir(&temp_dir)
            .output()
            .expect("cargo test runs");

        if !output.status.success() {
            panic!(
                "generated crate tests failed\nstdout:\n{}\nstderr:\n{}\nsource:\n{}",
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr),
                content
            );
        }

        fs::remove_dir_all(temp_dir).expect("remove temp crate");
    }

    fn generated_content() -> String {
        let request = request();
        let response = try_generate(&request).unwrap();
        assert_eq!(response.file.len(), 1);
        response.file[0]
            .content
            .as_ref()
            .expect("generated file has content")
            .clone()
    }

    fn request() -> CodeGeneratorRequest {
        CodeGeneratorRequest {
            file_to_generate: vec!["test/v1/test.proto".into()],
            proto_file: vec![test_file()],
            ..Default::default()
        }
    }

    fn test_file() -> FileDescriptorProto {
        FileDescriptorProto {
            name: Some("test/v1/test.proto".into()),
            package: Some("test.v1".into()),
            message_type: vec![
                DescriptorProto {
                    name: Some("TestRequest".into()),
                    field: vec![
                        field("data", 1, Type::TYPE_STRING, None),
                        field("test_type", 2, Type::TYPE_ENUM, Some(".test.v1.Tester")),
                        field("tester", 8, Type::TYPE_MESSAGE, Some(".test.v1.Nested")),
                    ],
                    ..Default::default()
                },
                DescriptorProto {
                    name: Some("Nested".into()),
                    ..Default::default()
                },
                DescriptorProto {
                    name: Some("EmptyRequest".into()),
                    ..Default::default()
                },
                DescriptorProto {
                    name: Some("TestResponse".into()),
                    ..Default::default()
                },
            ],
            enum_type: vec![EnumDescriptorProto {
                name: Some("Tester".into()),
                ..Default::default()
            }],
            service: vec![ServiceDescriptorProto {
                name: Some("TestService".into()),
                method: vec![
                    method(
                        "GetOne",
                        ".test.v1.TestRequest",
                        http_rule(2, "/test/{data}", None),
                    ),
                    method(
                        "DoTest",
                        ".test.v1.TestRequest",
                        http_rule(4, "/test/{data}/testing/{test_type}", Some("tester")),
                    ),
                    method(
                        "PatchAll",
                        ".test.v1.TestRequest",
                        http_rule(6, "/test", Some("*")),
                    ),
                    method("Ping", ".test.v1.EmptyRequest", http_rule(2, "/ping", None)),
                ],
                ..Default::default()
            }],
            ..Default::default()
        }
    }

    fn method(
        name: &str,
        input_type: &str,
        options: MessageField<MethodOptions>,
    ) -> MethodDescriptorProto {
        MethodDescriptorProto {
            name: Some(name.into()),
            input_type: Some(input_type.into()),
            output_type: Some(".test.v1.TestResponse".into()),
            options,
            ..Default::default()
        }
    }

    fn field(name: &str, number: i32, kind: Type, type_name: Option<&str>) -> FieldDescriptorProto {
        FieldDescriptorProto {
            name: Some(name.into()),
            number: Some(number),
            label: Some(Label::LABEL_OPTIONAL),
            r#type: Some(kind),
            type_name: type_name.map(str::to_owned),
            json_name: Some(name.into()),
            ..Default::default()
        }
    }

    fn http_rule(verb_field: u32, path: &str, body: Option<&str>) -> MessageField<MethodOptions> {
        let mut rule = Vec::new();
        Tag::new(verb_field, WireType::LengthDelimited).encode(&mut rule);
        buffa::types::encode_string(path, &mut rule);

        if let Some(body) = body {
            Tag::new(7, WireType::LengthDelimited).encode(&mut rule);
            buffa::types::encode_string(body, &mut rule);
        }

        let mut options = MethodOptions::default();
        options.__buffa_unknown_fields.push(UnknownField {
            number: 72_295_728,
            data: UnknownFieldData::LengthDelimited(rule),
        });
        MessageField::some(options)
    }

    fn temp_crate_dir() -> std::path::PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time")
            .as_nanos();
        std::env::temp_dir().join(format!(
            "connect2axum-codegen-{}-{nanos}",
            std::process::id()
        ))
    }

    fn temp_cargo_toml() -> &'static str {
        r#"[package]
name = "connect2axum-generated-check"
version = "0.0.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
"#
    }

    fn temp_lib_rs(generated: &str) -> String {
        let mut source = r#"extern crate self as axum;
extern crate self as buffa;
extern crate self as connect2axum;
extern crate self as connectrpc;
extern crate self as http;

	pub struct Json<T>(pub T);

	pub mod body {
	    pub use crate::bytes::Bytes;

	    #[derive(Clone, Debug, Default, Eq, PartialEq)]
	    pub enum BodyPayload {
	        #[default]
	        None,
	        Nested(crate::proto::test::v1::Nested),
	        TestRequest(crate::proto::test::v1::TestRequest),
	    }

	    #[derive(Clone, Debug, Eq, PartialEq)]
	    pub struct Body {
	        pub label: &'static str,
	        pub payload: BodyPayload,
	    }

	    impl Body {
	        pub fn from<T>(_value: T) -> Self {
	            Self::label("body")
	        }

	        pub fn label(label: &'static str) -> Self {
	            Self {
	                label,
	                payload: BodyPayload::None,
	            }
	        }

	        pub fn nested(value: crate::proto::test::v1::Nested) -> Self {
	            Self {
	                label: "body",
	                payload: BodyPayload::Nested(value),
	            }
	        }

	        pub fn test_request(value: crate::proto::test::v1::TestRequest) -> Self {
	            Self {
	                label: "body",
	                payload: BodyPayload::TestRequest(value),
	            }
	        }
	    }
	}

	pub mod bytes {
	    #[derive(Clone, Debug, Default, Eq, PartialEq)]
	    pub struct Bytes(pub crate::body::BodyPayload);

	    impl Bytes {
	        pub fn new() -> Self {
	            Self(crate::body::BodyPayload::None)
	        }
	    }
	}

	pub mod request {
	    #[derive(Clone, Debug, Default, Eq, PartialEq)]
	    pub struct Parts {
	        pub uri: crate::Uri,
	        pub headers: crate::HeaderMap,
	        pub extensions: crate::Extensions,
	    }
	}

	#[derive(Clone, Debug, Default, Eq, PartialEq)]
	pub struct Uri {
	    path: String,
	    query: Option<String>,
	}

	impl Uri {
	    pub fn new(path: impl Into<String>, query: Option<impl Into<String>>) -> Self {
	        Self {
	            path: path.into(),
	            query: query.map(Into::into),
	        }
	    }

	    pub fn path(&self) -> &str {
	        &self.path
	    }

	    pub fn query(&self) -> Option<&str> {
	        self.query.as_deref()
	    }
	}

	pub struct Request<B> {
	    parts: request::Parts,
	    body: B,
	}

	impl Request<body::Body> {
	    pub fn rest(
	        path: impl Into<String>,
	        query: Option<impl Into<String>>,
	        body: body::Body,
	    ) -> Self {
	        Self {
	            parts: request::Parts {
	                uri: Uri::new(path, query),
	                headers: HeaderMap,
	                extensions: Extensions,
	            },
	            body,
	        }
	    }
	}

	impl<B> Request<B> {
	    pub fn into_parts(self) -> (request::Parts, B) {
	        (self.parts, self.body)
	    }
	}

	pub trait FromFakePath {
	    fn from_path(path: &str) -> Self;
	}

	pub trait FromFakeQuery {
	    fn from_query(query: Option<&str>) -> Self;
	}

	pub trait FromFakeBody {
	    fn from_body(body: &bytes::Bytes) -> Self;
	}

	pub mod extract {
	    use std::future::{Ready, ready};

	    pub struct Path<T>(pub T);
	    pub struct Query<T>(pub T);
	    pub struct State<T>(pub T);

	    pub trait FromRequestParts<S>: Sized {
	        type Rejection;

	        fn from_request_parts(
	            parts: &mut crate::request::Parts,
	            _state: &S,
	        ) -> Ready<Result<Self, Self::Rejection>>;
	    }

	    impl<T, S> FromRequestParts<S> for Path<T>
	    where
	        T: crate::FromFakePath,
	    {
	        type Rejection = crate::ConnectError;

	        fn from_request_parts(
	            parts: &mut crate::request::Parts,
	            _state: &S,
	        ) -> Ready<Result<Self, Self::Rejection>> {
	            ready(Ok(Self(T::from_path(parts.uri.path()))))
	        }
	    }

	    impl<T> Query<T>
	    where
	        T: crate::FromFakeQuery,
	    {
	        pub fn try_from_uri(uri: &crate::Uri) -> Result<Self, crate::ConnectError> {
	            Ok(Self(T::from_query(uri.query())))
	        }
	    }
	}

pub mod routing {
    pub struct MethodRouter;

    pub fn delete<H>(_handler: H) -> MethodRouter {
        MethodRouter
    }

    pub fn get<H>(_handler: H) -> MethodRouter {
        MethodRouter
    }

    pub fn patch<H>(_handler: H) -> MethodRouter {
        MethodRouter
    }

    pub fn post<H>(_handler: H) -> MethodRouter {
        MethodRouter
    }

    pub fn put<H>(_handler: H) -> MethodRouter {
        MethodRouter
    }
}

pub struct Router;

impl Router {
    pub fn new() -> Self {
        Self
    }

    pub fn route(self, _path: &str, _method: routing::MethodRouter) -> Self {
        self
    }

    pub fn with_state<S>(self, _state: S) -> Self {
        self
    }
}

	#[derive(Clone, Debug, Default, Eq, PartialEq)]
	pub struct HeaderMap;

	#[derive(Clone, Debug, Default, Eq, PartialEq)]
	pub struct Extensions;
	pub struct RequestContext;

pub fn request_context(_headers: HeaderMap, _extensions: Extensions) -> RequestContext {
    RequestContext
}

pub fn owned_view<V>(
    _message: &<V as view::MessageView<'static>>::Owned,
) -> Result<view::OwnedView<V>, ConnectError>
where
    V: view::MessageView<'static>,
    V::Owned: Clone,
{
    Ok(view::OwnedView(_message.clone(), ::std::marker::PhantomData))
}

	pub fn owned_view_from_bytes<V>(_bytes: bytes::Bytes) -> Result<view::OwnedView<V>, ConnectError>
	where
	    V: view::MessageView<'static>,
	    V::Owned: Default,
{
    Ok(view::OwnedView(
        V::Owned::default(),
        ::std::marker::PhantomData,
	    ))
	}

	pub fn owned_view_from_wire<V>(_request: WireRequest) -> Result<view::OwnedView<V>, ConnectError>
	where
	    V: view::MessageView<'static>,
	    V::Owned: Default,
	{
	    owned_view_from_bytes::<V>(bytes::Bytes::new())
	}

	pub struct WireRequest;

	impl WireRequest {
	    pub fn new() -> Self {
	        Self
	    }

	    pub fn push_path_string(
	        &mut self,
	        _field_number: u32,
	        _encoded_value: &str,
	    ) -> Result<(), ConnectError> {
	        Ok(())
	    }

	    pub fn push_query_string(
	        &mut self,
	        _raw_query: Option<&str>,
	        _json_name: &str,
	        _proto_name: &str,
	        _field_number: u32,
	    ) {
	    }

	    pub fn push_json_body_string(
	        &mut self,
	        _body: &bytes::Bytes,
	        _field_number: u32,
	    ) -> Result<(), ConnectError> {
	        Ok(())
	    }
	}

	pub struct PathDecoder<'a> {
	    path: &'a str,
	}

	impl<'a> PathDecoder<'a> {
	    pub fn new(path: &'a str) -> Self {
	        Self { path }
	    }

	    pub fn capture(&mut self, _prefix: &str, _suffix: &str) -> Result<&'a str, ConnectError> {
	        Ok(self.path)
	    }
	}

	pub async fn body_bytes(body: body::Body) -> Result<bytes::Bytes, ConnectError> {
	    Ok(bytes::Bytes(body.payload))
	}

	pub fn json_body<T>(body: &bytes::Bytes) -> Result<T, ConnectError>
	where
	    T: FromFakeBody,
	{
	    Ok(T::from_body(body))
	}

	pub fn error_response(_err: ConnectError) -> Response<body::Body> {
	    Response {
	        status: 400,
	        body: body::Body::label("error"),
	    }
	}

pub fn service_response<M, B>(_response: ServiceResult<B>) -> Response<body::Body>
where
    B: Encodable<M>,
{
    match _response {
	        Ok(_) => Response {
	            status: 200,
	            body: body::Body::label("ok"),
	        },
        Err(err) => error_response(err),
    }
}

pub fn compatible_service_response<M, B>(_response: ServiceResult<B>) -> Response<body::Body>
where
    B: Encodable<M>,
{
    service_response::<M, B>(_response)
}

pub fn json_from_proto<M>(_bytes: bytes::Bytes) -> Result<bytes::Bytes, ConnectError> {
    Ok(bytes::Bytes::new())
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Response<T> {
    pub status: u16,
    pub body: T,
}

impl<T> Response<T> {
    pub fn new(body: T) -> Self {
        Self { status: 200, body }
    }
}

#[derive(Clone, Debug)]
pub struct ConnectError;

	impl ConnectError {
	    pub fn unimplemented(_message: impl Into<String>) -> Self {
	        Self
	    }

	    pub fn invalid_argument(_message: impl Into<String>) -> Self {
	        Self
	    }
	}

	impl std::fmt::Display for ConnectError {
	    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
	        formatter.write_str("connect error")
	    }
	}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CodecFormat {
    Proto,
    Json,
}

pub type ServiceResult<B> = Result<Response<B>, ConnectError>;

pub trait Encodable<M> {}

	pub trait JsonCompatibleBody<M> {
	    fn encode_proto(&self) -> bytes::Bytes;

	    fn encode_compatible(&self, _codec: CodecFormat) -> Result<bytes::Bytes, ConnectError> {
	        Ok(self.encode_proto())
	    }
	}

pub trait ViewEncode {
    fn encode_to_bytes(&self) -> bytes::Bytes {
        bytes::Bytes::new()
    }
}

pub mod view {
    pub trait MessageView<'a> {
        type Owned;
    }

    pub struct OwnedView<V: MessageView<'static>>(
        pub V::Owned,
        pub ::std::marker::PhantomData<V>,
    );

    impl<V: MessageView<'static>> ::std::ops::Deref for OwnedView<V> {
        type Target = V;

        fn deref(&self) -> &Self::Target {
            unreachable!("generated compile fixture never dereferences fake OwnedView")
        }
    }
}

pub mod connect {
    pub mod test {
        pub mod v1 {
            pub trait TestService: Send + Sync + 'static {
                fn get_one<'a>(
                    &'a self,
                    _ctx: crate::RequestContext,
                    _request: crate::view::OwnedView<
                        crate::proto::test::v1::__buffa::view::TestRequestView<'static>,
                    >,
                ) -> impl ::std::future::Future<
                    Output = crate::ServiceResult<crate::proto::test::v1::TestResponse>,
                > + Send + 'a;

                fn do_test<'a>(
                    &'a self,
                    _ctx: crate::RequestContext,
                    _request: crate::view::OwnedView<
                        crate::proto::test::v1::__buffa::view::TestRequestView<'static>,
                    >,
                ) -> impl ::std::future::Future<
                    Output = crate::ServiceResult<crate::proto::test::v1::TestResponse>,
                > + Send + 'a;

                fn patch_all<'a>(
                    &'a self,
                    _ctx: crate::RequestContext,
                    _request: crate::view::OwnedView<
                        crate::proto::test::v1::__buffa::view::TestRequestView<'static>,
                    >,
                ) -> impl ::std::future::Future<
                    Output = crate::ServiceResult<crate::proto::test::v1::TestResponse>,
                > + Send + 'a;

                fn ping<'a>(
                    &'a self,
                    _ctx: crate::RequestContext,
                    _request: crate::view::OwnedView<
                        crate::proto::test::v1::__buffa::view::EmptyRequestView<'static>,
                    >,
                ) -> impl ::std::future::Future<
                    Output = crate::ServiceResult<crate::proto::test::v1::TestResponse>,
                > + Send + 'a;
            }
        }
    }
}

pub mod proto {
    pub mod test {
        pub mod v1 {
            #[derive(Clone, Debug, Default, Eq, PartialEq, serde::Deserialize)]
            pub struct TestRequest {
                pub data: ::std::string::String,
                pub test_type: Tester,
                pub tester: Nested,
            }

            #[derive(Clone, Debug, Default, Eq, PartialEq, serde::Deserialize)]
            pub struct Nested {
                pub data: ::std::string::String,
            }

            #[derive(Clone, Debug, Default, Eq, PartialEq, serde::Deserialize)]
            pub enum Tester {
                #[default]
                Unknown,
                Known,
            }

            #[derive(Clone, Debug, Default, Eq, PartialEq, serde::Deserialize)]
            pub struct EmptyRequest;

            #[derive(Clone, Debug, Default, Eq, PartialEq)]
            pub struct TestResponse;

            impl crate::Encodable<TestResponse> for TestResponse {}

            pub mod __buffa {
                pub mod view {
                    pub struct TestRequestView<'a>(::std::marker::PhantomData<&'a ()>);
                    pub struct EmptyRequestView<'a>(::std::marker::PhantomData<&'a ()>);
                    pub struct TestResponseView<'a>(::std::marker::PhantomData<&'a ()>);
                }
            }

            impl crate::view::MessageView<'static> for __buffa::view::TestRequestView<'static> {
                type Owned = TestRequest;
            }

            impl crate::view::MessageView<'static> for __buffa::view::EmptyRequestView<'static> {
                type Owned = EmptyRequest;
            }

            impl crate::view::MessageView<'static> for __buffa::view::TestResponseView<'static> {
                type Owned = TestResponse;
            }

            impl crate::ViewEncode for __buffa::view::TestResponseView<'_> {}
        }
    }
}

"#
        .to_owned();
        source.push_str(generated);
        source.push_str(
            r#"

	impl crate::FromFakePath for String {
	    fn from_path(path: &str) -> Self {
	        path.trim_matches('/')
	            .split('/')
	            .nth(1)
	            .unwrap_or_default()
	            .to_owned()
	    }
	}

	impl crate::FromFakePath for (String, crate::proto::test::v1::Tester) {
	    fn from_path(path: &str) -> Self {
	        let mut segments = path.trim_matches('/').split('/');
	        let data = segments.nth(1).unwrap_or_default().to_owned();
	        let tester = match segments.nth(1).unwrap_or_default() {
	            "known" | "Known" => crate::proto::test::v1::Tester::Known,
	            _ => crate::proto::test::v1::Tester::Unknown,
	        };
	        (data, tester)
	    }
	}

	impl crate::FromFakeQuery for crate::test_service_rest::TestRequestQuery__ {
	    fn from_query(query: Option<&str>) -> Self {
	        let query = query.unwrap_or_default();
	        Self {
	            test_type: if query.contains("known") || query.contains("Known") {
	                crate::proto::test::v1::Tester::Known
	            } else {
	                crate::proto::test::v1::Tester::Unknown
	            },
	            tester: crate::proto::test::v1::Nested {
	                data: if query.contains("query") {
	                    "query".to_owned()
	                } else {
	                    String::new()
	                },
	            },
	        }
	    }
	}

	impl crate::FromFakeBody for crate::proto::test::v1::Nested {
	    fn from_body(body: &crate::bytes::Bytes) -> Self {
	        match &body.0 {
	            crate::body::BodyPayload::Nested(value) => value.clone(),
	            _ => Self::default(),
	        }
	    }
	}

	impl crate::FromFakeBody for crate::proto::test::v1::TestRequest {
	    fn from_body(body: &crate::bytes::Bytes) -> Self {
	        match &body.0 {
	            crate::body::BodyPayload::TestRequest(value) => value.clone(),
	            _ => Self::default(),
	        }
	    }
	}

	#[cfg(test)]
	mod generated_handler_tests {
    use std::future::Future;
    use std::pin::Pin;
    use std::sync::{Arc, Mutex};
    use std::task::{Context, Poll};

	    use crate::body::Body;
	    use crate::extract::State;
	    use crate::proto::test::v1::{EmptyRequest, Nested, TestRequest, TestResponse, Tester};
	    use crate::{Request, Response, ServiceResult};

    #[derive(Clone, Debug, Eq, PartialEq)]
    enum Call {
        Test(TestRequest),
        Empty(EmptyRequest),
    }

    #[derive(Default)]
    struct RecordingService {
        calls: Mutex<Vec<Call>>,
        fail: bool,
    }

    impl RecordingService {
        fn failing() -> Self {
            Self {
                calls: Mutex::new(Vec::new()),
                fail: true,
            }
        }

        fn calls(&self) -> Vec<Call> {
            self.calls.lock().expect("calls lock").clone()
        }

        fn respond(&self, call: Call) -> ServiceResult<TestResponse> {
            if self.fail {
                Err(crate::ConnectError)
            } else {
                self.calls.lock().expect("calls lock").push(call);
                Ok(Response::new(TestResponse))
            }
        }
    }

    impl crate::connect::test::v1::TestService for RecordingService {
        fn get_one<'a>(
            &'a self,
            _ctx: crate::RequestContext,
            request: crate::view::OwnedView<
                crate::proto::test::v1::__buffa::view::TestRequestView<'static>,
            >,
        ) -> impl Future<Output = ServiceResult<TestResponse>> + Send + 'a {
            async move { self.respond(Call::Test(request.0)) }
        }

        fn do_test<'a>(
            &'a self,
            _ctx: crate::RequestContext,
            request: crate::view::OwnedView<
                crate::proto::test::v1::__buffa::view::TestRequestView<'static>,
            >,
        ) -> impl Future<Output = ServiceResult<TestResponse>> + Send + 'a {
            async move { self.respond(Call::Test(request.0)) }
        }

        fn patch_all<'a>(
            &'a self,
            _ctx: crate::RequestContext,
            request: crate::view::OwnedView<
                crate::proto::test::v1::__buffa::view::TestRequestView<'static>,
            >,
        ) -> impl Future<Output = ServiceResult<TestResponse>> + Send + 'a {
            async move { self.respond(Call::Test(request.0)) }
        }

        fn ping<'a>(
            &'a self,
            _ctx: crate::RequestContext,
            request: crate::view::OwnedView<
                crate::proto::test::v1::__buffa::view::EmptyRequestView<'static>,
            >,
        ) -> impl Future<Output = ServiceResult<TestResponse>> + Send + 'a {
            async move { self.respond(Call::Empty(request.0)) }
        }
    }

    #[test]
    fn successful_unary_request_reconstructs_path_and_query() {
        let service = Arc::new(RecordingService::default());

	        let response = block_on(crate::test_service_rest::get_one(
	            State(service.clone()),
	            Request::rest(
	                "/test/alpha",
	                Some("test_type=known&tester=query"),
	                Body::label("empty"),
	            ),
	        ));

        assert_eq!(response.status, 200);
        assert_eq!(
            service.calls(),
            vec![Call::Test(TestRequest {
                data: "alpha".to_owned(),
                test_type: Tester::Known,
                tester: Nested {
                    data: "query".to_owned(),
                },
            })]
        );
    }

    #[test]
    fn service_error_response_is_mapped() {
        let service = Arc::new(RecordingService::failing());

	        let response = block_on(crate::test_service_rest::get_one(
	            State(service),
	            Request::rest(
	                "/test/alpha",
	                Some("test_type=known&tester=query"),
	                Body::label("empty"),
	            ),
	        ));

	        assert_eq!(response.status, 400);
	        assert_eq!(response.body, crate::body::Body::label("error"));
    }

    #[test]
    fn path_and_body_request_is_reconstructed() {
        let service = Arc::new(RecordingService::default());

	        let response = block_on(crate::test_service_rest::do_test(
	            State(service.clone()),
	            Request::rest(
	                "/test/alpha/testing/known",
	                None::<&str>,
	                Body::nested(Nested {
	                    data: "body".to_owned(),
	                }),
	            ),
	        ));

        assert_eq!(response.status, 200);
        assert_eq!(
            service.calls(),
            vec![Call::Test(TestRequest {
                data: "alpha".to_owned(),
                test_type: Tester::Known,
                tester: Nested {
                    data: "body".to_owned(),
                },
            })]
        );
    }

    #[test]
    fn body_star_request_is_forwarded_verbatim() {
        let service = Arc::new(RecordingService::default());
        let request = TestRequest {
            data: "whole".to_owned(),
            test_type: Tester::Known,
            tester: Nested {
                data: "body".to_owned(),
            },
        };

	        let response = block_on(crate::test_service_rest::patch_all(
	            State(service.clone()),
	            Request::rest("/test", None::<&str>, Body::test_request(request.clone())),
	        ));

        assert_eq!(response.status, 200);
        assert_eq!(service.calls(), vec![Call::Test(request)]);
    }

    #[test]
    fn empty_request_uses_default_owned_message() {
        let service = Arc::new(RecordingService::default());

	        let response = block_on(crate::test_service_rest::ping(
	            State(service.clone()),
	            Request::rest("/ping", None::<&str>, Body::label("empty")),
	        ));

        assert_eq!(response.status, 200);
        assert_eq!(service.calls(), vec![Call::Empty(EmptyRequest)]);
    }

    fn block_on<F: Future>(future: F) -> F::Output {
        let mut future = Pin::from(Box::new(future));
        let waker = std::task::Waker::noop();
        let mut context = Context::from_waker(waker);

        loop {
            match future.as_mut().poll(&mut context) {
                Poll::Ready(output) => return output,
                Poll::Pending => std::thread::yield_now(),
            }
        }
    }
}
"#,
        );
        source
    }
}
