//! Protoc/Buf code generation for `connect2axum`.
//!

mod error;
mod options;

use connectrpc_codegen::plugin::CodeGeneratorResponseFile;
use uni_error::UniError;

pub use connectrpc_codegen::plugin::{CodeGeneratorRequest, CodeGeneratorResponse};
pub use error::{CodegenErrKind, CodegenResult};
pub use options::{CodegenOptions, ServiceState};

/// Generate a protoc plugin response for a request.
///
/// Errors are returned through the protoc plugin error field so `buf generate`
/// and `protoc` can display them as compiler-plugin failures.
#[must_use]
pub fn generate(request: &CodeGeneratorRequest) -> CodeGeneratorResponse {
    match try_generate(request) {
        Ok(response) => response,
        Err(err) => CodeGeneratorResponse {
            error: Some(err.to_string()),
            ..Default::default()
        },
    }
}

/// Generate a protoc plugin response, returning typed project errors.
pub fn try_generate(request: &CodeGeneratorRequest) -> CodegenResult<CodeGeneratorResponse> {
    let _options = CodegenOptions::parse(request.parameter.as_deref())?;
    let files = request
        .file_to_generate
        .iter()
        .map(|file_name| generate_placeholder_file(request, file_name))
        .collect::<CodegenResult<Vec<_>>>()?;

    Ok(CodeGeneratorResponse {
        file: files,
        ..Default::default()
    })
}

fn generate_placeholder_file(
    request: &CodeGeneratorRequest,
    file_name: &str,
) -> CodegenResult<CodeGeneratorResponseFile> {
    let proto_file = request
        .proto_file
        .iter()
        .find(|file| file.name.as_deref() == Some(file_name))
        .ok_or_else(|| {
            UniError::from_kind_context(
                CodegenErrKind::FileToGenerateNotFound,
                format!("file_to_generate {file_name:?} was not present in proto_file"),
            )
        })?;

    let output_name = output_file_name(file_name);
    let package = proto_file.package.as_deref().unwrap_or_default();
    let content = format!(
        "// @generated by connect2axum.\n\
         // Phase 2 placeholder for {file_name}.\n\
         // package: {package}\n"
    );

    Ok(CodeGeneratorResponseFile {
        name: Some(output_name),
        content: Some(content),
        ..Default::default()
    })
}

fn output_file_name(proto_file_name: &str) -> String {
    let stem = proto_file_name
        .strip_suffix(".proto")
        .unwrap_or(proto_file_name);
    format!("{stem}.connect2axum.rs")
}

#[cfg(test)]
mod tests {
    use buffa::Message as _;
    use connectrpc_codegen::codegen::descriptor::FileDescriptorProto;

    use super::{CodeGeneratorRequest, CodeGeneratorResponse, generate, try_generate};

    #[test]
    fn empty_request_generates_empty_response() {
        let request = CodeGeneratorRequest::default();

        let response = generate(&request);

        assert!(response.file.is_empty());
        assert!(response.error.is_none());
    }

    #[test]
    fn unknown_option_generates_plugin_error_response() {
        let request = CodeGeneratorRequest {
            parameter: Some("surprise=true".into()),
            ..Default::default()
        };

        let response = generate(&request);

        assert!(response.file.is_empty());
        assert!(
            response
                .error
                .as_deref()
                .is_some_and(|err| err.contains("unknown plugin option: surprise"))
        );
    }

    #[test]
    fn generates_deterministic_placeholder_file_names() {
        let request = CodeGeneratorRequest {
            file_to_generate: vec!["hello/v1/hello.proto".into(), "echo.proto".into()],
            proto_file: vec![
                FileDescriptorProto {
                    name: Some("hello/v1/hello.proto".into()),
                    package: Some("hello.v1".into()),
                    ..Default::default()
                },
                FileDescriptorProto {
                    name: Some("echo.proto".into()),
                    package: Some("echo.v1".into()),
                    ..Default::default()
                },
            ],
            ..Default::default()
        };

        let response = try_generate(&request).unwrap();

        let names = response
            .file
            .iter()
            .map(|file| file.name.as_deref())
            .collect::<Vec<_>>();
        assert_eq!(
            names,
            vec![
                Some("hello/v1/hello.connect2axum.rs"),
                Some("echo.connect2axum.rs")
            ]
        );
    }

    #[test]
    fn missing_file_to_generate_is_a_typed_error() {
        let request = CodeGeneratorRequest {
            file_to_generate: vec!["missing.proto".into()],
            proto_file: vec![],
            ..Default::default()
        };

        let err = try_generate(&request).unwrap_err();

        assert!(
            err.to_string()
                .contains("file_to_generate \"missing.proto\" was not present in proto_file")
        );
    }

    #[test]
    fn plugin_protocol_messages_round_trip() {
        let request = CodeGeneratorRequest::default();
        let request_bytes = request.encode_to_vec();
        let decoded_request =
            CodeGeneratorRequest::decode_from_slice(&request_bytes).expect("request decodes");

        let response = generate(&decoded_request);
        let response_bytes = response.encode_to_vec();
        let decoded_response =
            CodeGeneratorResponse::decode_from_slice(&response_bytes).expect("response decodes");

        assert!(decoded_response.file.is_empty());
        assert!(decoded_response.error.is_none());
    }
}
