//! Protoc/Buf code generation for `connect2axum`.
//!

mod error;
mod http;
mod ir;
mod options;
mod resolver;
mod shape;

use connectrpc_codegen::plugin::CodeGeneratorResponseFile;
use flexstr::SharedStr;
use uni_error::UniError;

pub use connectrpc_codegen::plugin::{CodeGeneratorRequest, CodeGeneratorResponse};
pub use error::{CodegenErrKind, CodegenResult};
pub use ir::{
    CommentSet, DescriptorIr, Field, FieldKind, FieldLabel, HttpBinding, HttpBody, HttpVerb,
    Message, Method, ProtoFile, Service, build_ir,
};
pub use options::{CodegenOptions, ServiceState};
pub use resolver::{RustPath, TypeResolver};
pub use shape::{
    FieldAssignment, FieldSource, FileShapes, GeneratedDto, GeneratedDtoKind, RequestPartShape,
    RequestReconstruction, RequestShape, ShapeField, plan_file_shapes,
};

/// Generate a protoc plugin response for a request.
///
/// Errors are returned through the protoc plugin error field so `buf generate`
/// and `protoc` can display them as compiler-plugin failures.
#[must_use]
pub fn generate(request: &CodeGeneratorRequest) -> CodeGeneratorResponse {
    match try_generate(request) {
        Ok(response) => response,
        Err(err) => CodeGeneratorResponse {
            error: Some(err.to_string()),
            ..Default::default()
        },
    }
}

/// Generate a protoc plugin response, returning typed project errors.
pub fn try_generate(request: &CodeGeneratorRequest) -> CodegenResult<CodeGeneratorResponse> {
    let options = CodegenOptions::parse(request.parameter.as_deref())?;
    let ir = build_ir(request)?;
    let files = request
        .file_to_generate
        .iter()
        .map(|file_name| generate_placeholder_file(&ir, file_name, &options))
        .collect::<CodegenResult<Vec<_>>>()?
        .into_iter()
        .flatten()
        .collect();

    Ok(CodeGeneratorResponse {
        file: files,
        ..Default::default()
    })
}

fn generate_placeholder_file(
    ir: &DescriptorIr,
    file_name: &str,
    options: &CodegenOptions,
) -> CodegenResult<Option<CodeGeneratorResponseFile>> {
    let proto_file = ir.file(file_name).ok_or_else(|| {
        UniError::from_kind_context(
            CodegenErrKind::FileToGenerateNotFound,
            format!("file_to_generate {file_name:?} was not present in proto_file"),
        )
    })?;

    if !proto_file.has_http_bindings() {
        return Ok(None);
    }

    let output_name = output_file_name(proto_file.name.as_ref());
    let content = placeholder_content(ir, proto_file, options)?;

    Ok(Some(CodeGeneratorResponseFile {
        name: Some(output_name),
        content: Some(content),
        ..Default::default()
    }))
}

fn output_file_name(proto_file_name: &str) -> String {
    let stem = proto_file_name
        .strip_suffix(".proto")
        .unwrap_or(proto_file_name);
    format!("{stem}.connect2axum.rs")
}

fn placeholder_content(
    ir: &DescriptorIr,
    proto_file: &ProtoFile,
    options: &CodegenOptions,
) -> CodegenResult<String> {
    let shapes = plan_file_shapes(ir, proto_file, options)?;
    let mut content = format!(
        "// @generated by connect2axum.\n\
         // Phase 4 request-shape placeholder for {}.\n\
         // package: {}\n",
        proto_file.name.as_ref(),
        proto_file.package.as_ref()
    );

    for service in &proto_file.services {
        for method in &service.methods {
            let Some(binding) = &method.http else {
                continue;
            };

            let path_variables = join_shared_strs(&binding.path_variables);
            content.push_str(&format!(
                "// route: {} {} -> {} body: {} path_fields: [{}]\n",
                binding.verb.as_str(),
                binding.path.as_ref(),
                method.full_name.as_ref(),
                binding.body.description(),
                path_variables
            ));
        }
    }

    for shape in &shapes.request_shapes {
        content.push_str(&format!(
            "// shape: {} request={} view={} body={} query={} reconstruction={}\n",
            shape.method.as_ref(),
            shape.request_type.as_str(),
            shape.request_view_type.as_str(),
            shape
                .body_shape
                .as_ref()
                .map_or_else(|| "none".to_owned(), RequestPartShape::description),
            shape
                .query_shape
                .as_ref()
                .map_or_else(|| "none".to_owned(), RequestPartShape::description),
            reconstruction_description(&shape.reconstruction),
        ));
    }

    for dto in &shapes.generated_dtos {
        let fields = dto
            .fields
            .iter()
            .map(|field| {
                format!(
                    "{}: {}",
                    field.field.name.as_ref(),
                    field.rust_type.as_str()
                )
            })
            .collect::<Vec<_>>()
            .join(", ");
        content.push_str(&format!(
            "// dto: {:?} {} [{}]\n",
            dto.kind,
            dto.name.as_ref(),
            fields
        ));
    }

    Ok(content)
}

fn join_shared_strs(values: &[SharedStr]) -> String {
    values
        .iter()
        .map(|value| value.as_ref())
        .collect::<Vec<_>>()
        .join(", ")
}

fn reconstruction_description(reconstruction: &RequestReconstruction) -> String {
    match reconstruction {
        RequestReconstruction::Empty => "empty".to_owned(),
        RequestReconstruction::VerbatimBody => "verbatim_body".to_owned(),
        RequestReconstruction::VerbatimQuery => "verbatim_query".to_owned(),
        RequestReconstruction::FromParts { fields } => fields
            .iter()
            .map(|field| format!("{}:{:?}", field.field.as_ref(), field.source))
            .collect::<Vec<_>>()
            .join(","),
    }
}

#[cfg(test)]
mod tests {
    use buffa::Message as _;
    use buffa::encoding::{Tag, WireType};
    use buffa::{MessageField, UnknownField, UnknownFieldData};
    use connectrpc_codegen::codegen::descriptor::{
        DescriptorProto, FieldDescriptorProto, FileDescriptorProto, MethodDescriptorProto,
        MethodOptions, ServiceDescriptorProto,
        field_descriptor_proto::{Label, Type},
    };

    use super::{CodeGeneratorRequest, CodeGeneratorResponse, generate, try_generate};

    #[test]
    fn empty_request_generates_empty_response() {
        let request = CodeGeneratorRequest::default();

        let response = generate(&request);

        assert!(response.file.is_empty());
        assert!(response.error.is_none());
    }

    #[test]
    fn unknown_option_generates_plugin_error_response() {
        let request = CodeGeneratorRequest {
            parameter: Some("surprise=true".into()),
            ..Default::default()
        };

        let response = generate(&request);

        assert!(response.file.is_empty());
        assert!(
            response
                .error
                .as_deref()
                .is_some_and(|err| err.contains("unknown plugin option: surprise"))
        );
    }

    #[test]
    fn generates_deterministic_placeholder_file_names_for_files_with_http_bindings() {
        let request = CodeGeneratorRequest {
            file_to_generate: vec!["hello/v1/hello.proto".into(), "echo.proto".into()],
            proto_file: vec![
                test_file("hello/v1/hello.proto", "hello.v1", true),
                test_file("echo.proto", "echo.v1", true),
            ],
            ..Default::default()
        };

        let response = try_generate(&request).unwrap();

        let names = response
            .file
            .iter()
            .map(|file| file.name.as_deref())
            .collect::<Vec<_>>();
        assert_eq!(
            names,
            vec![
                Some("hello/v1/hello.connect2axum.rs"),
                Some("echo.connect2axum.rs")
            ]
        );
    }

    #[test]
    fn skips_files_without_http_bindings() {
        let request = CodeGeneratorRequest {
            file_to_generate: vec!["hello/v1/hello.proto".into()],
            proto_file: vec![test_file("hello/v1/hello.proto", "hello.v1", false)],
            ..Default::default()
        };

        let response = try_generate(&request).unwrap();

        assert!(response.file.is_empty());
    }

    #[test]
    fn missing_file_to_generate_is_a_typed_error() {
        let request = CodeGeneratorRequest {
            file_to_generate: vec!["missing.proto".into()],
            proto_file: vec![],
            ..Default::default()
        };

        let err = try_generate(&request).unwrap_err();

        assert!(
            err.to_string()
                .contains("file_to_generate \"missing.proto\" was not present in proto_file")
        );
    }

    #[test]
    fn plugin_protocol_messages_round_trip() {
        let request = CodeGeneratorRequest::default();
        let request_bytes = request.encode_to_vec();
        let decoded_request =
            CodeGeneratorRequest::decode_from_slice(&request_bytes).expect("request decodes");

        let response = generate(&decoded_request);
        let response_bytes = response.encode_to_vec();
        let decoded_response =
            CodeGeneratorResponse::decode_from_slice(&response_bytes).expect("response decodes");

        assert!(decoded_response.file.is_empty());
        assert!(decoded_response.error.is_none());
    }

    fn test_file(name: &str, package: &str, with_http_binding: bool) -> FileDescriptorProto {
        FileDescriptorProto {
            name: Some(name.into()),
            package: Some(package.into()),
            message_type: vec![DescriptorProto {
                name: Some("HelloRequest".into()),
                field: vec![FieldDescriptorProto {
                    name: Some("name".into()),
                    number: Some(1),
                    label: Some(Label::LABEL_OPTIONAL),
                    r#type: Some(Type::TYPE_STRING),
                    json_name: Some("name".into()),
                    ..Default::default()
                }],
                ..Default::default()
            }],
            service: vec![ServiceDescriptorProto {
                name: Some("HelloService".into()),
                method: vec![MethodDescriptorProto {
                    name: Some("SayHello".into()),
                    input_type: Some(format!(".{package}.HelloRequest")),
                    output_type: Some(format!(".{package}.HelloResponse")),
                    options: if with_http_binding {
                        method_options()
                    } else {
                        MessageField::none()
                    },
                    ..Default::default()
                }],
                ..Default::default()
            }],
            ..Default::default()
        }
    }

    fn method_options() -> MessageField<MethodOptions> {
        let mut rule = Vec::new();
        Tag::new(2, WireType::LengthDelimited).encode(&mut rule);
        buffa::types::encode_string("/hello/{name}", &mut rule);

        let mut options = MethodOptions::default();
        options.__buffa_unknown_fields.push(UnknownField {
            number: 72_295_728,
            data: UnknownFieldData::LengthDelimited(rule),
        });
        MessageField::some(options)
    }
}
